name: deploy-manifests

on:
<<<<<<< HEAD:.github/workflows/deploy-manifest.yaml
  push:
    branches:
      - master

=======
  workflow_run:
    workflows: ["deploy"]
    types:
      - completed
>>>>>>> 464b3390118db35f1e1ffb34fa4f7c283b2428ec:.github/workflows/deploy-manifest.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save pony-express-project
<<<<<<< HEAD:.github/workflows/deploy-manifest.yaml
      - run: kubectl apply -f ./infra/k8s && kubectl apply -f ./infra/k8s-prod
=======
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
      
  
>>>>>>> 464b3390118db35f1e1ffb34fa4f7c283b2428ec:.github/workflows/deploy-manifest.yml
