name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker push kyouma337/pony-express-project
      - uses: digitalocean/action-doctrl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save pony-express-project
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
      
  
