name: deploy-manifests

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'

 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save pony-express-project
      - run: ls -R
      - run: kubectl apply -f infra/k8s-prod
      - run: kubectl apply -f infra/k8s
      
  
